const $=id=>document.getElementById(id), chat=$("chat"), type=$("type"), rows=$("rows"), empty=$("empty");
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const get=async url=>{const r=await fetch(url);if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()};
const query=new URLSearchParams(location.search), requestedChat=query.get("chat"), requestedKind=query.get("kind"), requestedUid=query.get("uid");
const validUid=value=>/^[0-9]{6,12}$/.test(value||"");
const validKind=value=>["deadly_assault","shiyu_defense"].includes(value);
function updateUrl(uid){const next=new URLSearchParams();if(chat.value)next.set("chat",chat.value);next.set("kind",type.value);if(validUid(uid))next.set("uid",uid);history.replaceState(null,"",`${location.pathname}?${next}`)}
async function loadChats(){try{const data=await get("/api/chats");chat.innerHTML=data.map(x=>`<option value="${x.chat_id}">Чат ${x.chat_id} · ${x.user_count} игр.</option>`).join("");const knownChat=data.some(x=>String(x.chat_id)===requestedChat);if(knownChat)chat.value=requestedChat;if(validKind(requestedKind))type.value=requestedKind;if(data.length){await loadBoard();if(validUid(requestedUid))await loadHistory(requestedUid)}else $("summary").textContent="Нет подключённых чатов"}catch(e){$("summary").textContent="Не удалось загрузить данные"}}
async function loadBoard(){if(!chat.value)return;rows.innerHTML="";empty.hidden=true;try{const data=await get(`/api/chats/${encodeURIComponent(chat.value)}/leaderboard/${type.value}`);$("summary").textContent=`${data.length} результатов · нажмите на игрока, чтобы увидеть историю`;rows.innerHTML=data.map((x,i)=>`<tr data-uid="${esc(x.uid)}"><td>${i+1}</td><td class="player">${esc(x.nickname||"Без имени")}</td><td class="uid">${esc(x.uid)}</td><td class="number">${Number(x.total_score).toLocaleString("ru")}</td></tr>`).join("");empty.hidden=data.length!==0}catch(e){$("summary").textContent="Не удалось загрузить рейтинг"}}
function draw(data){if(!data.length){$("chart").innerHTML='<p class="empty">История пока пуста.</p>';return}const w=900,h=260,p=35,scores=data.map(x=>Number(x.total_score)),min=Math.min(...scores),max=Math.max(...scores),span=Math.max(max-min,1),pts=data.map((x,i)=>({x:p+i*(w-2*p)/Math.max(data.length-1,1),y:p+(max-Number(x.total_score))*(h-2*p)/span,d:x}));$("chart").innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="График результатов"><line class="chart-grid" x1="${p}" y1="${p}" x2="${p}" y2="${h-p}"/><line class="chart-grid" x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}"/><polyline class="chart-line" points="${pts.map(q=>`${q.x},${q.y}`).join(" ")}"/>${pts.map(q=>`<circle class="chart-dot" cx="${q.x}" cy="${q.y}" r="5"><title>${esc(q.d.endgame_type)}: ${q.d.total_score}</title></circle>`).join("")}<text class="chart-label" x="${p}" y="${p-10}">${max.toLocaleString("ru")}</text><text class="chart-label" x="${p}" y="${h-8}">${min.toLocaleString("ru")}</text></svg><div class="legend"><span>${data.length} снимков</span><span>${esc(data[0].season_start)} — ${esc(data[data.length-1].season_end)}</span></div>`}
async function loadHistory(uid){if(!validUid(uid))return;$("uid").value=uid;updateUrl(uid);try{const data=await get(`/api/users/${encodeURIComponent(uid)}/history`);draw(data.filter(x=>x.endgame_type===type.value))}catch(e){$("chart").innerHTML='<p class="empty">Не удалось загрузить историю.</p>'}}
chat.addEventListener("change",()=>{updateUrl($("uid").value);loadBoard()});type.addEventListener("change",()=>{updateUrl($("uid").value);loadBoard();if(validUid($("uid").value))loadHistory($("uid").value)});rows.addEventListener("click",e=>{const tr=e.target.closest("tr");if(tr)loadHistory(tr.dataset.uid)});$("history-form").addEventListener("submit",e=>{e.preventDefault();if($("uid").reportValidity()&&validUid($("uid").value))loadHistory($("uid").value)});loadChats();
